// Generated by gencpp from file serial_test/velocity.msg
// DO NOT EDIT!


#ifndef SERIAL_TEST_MESSAGE_VELOCITY_H
#define SERIAL_TEST_MESSAGE_VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_test
{
template <class ContainerAllocator>
struct velocity_
{
  typedef velocity_<ContainerAllocator> Type;

  velocity_()
    : VelocityMotor(0)  {
    }
  velocity_(const ContainerAllocator& _alloc)
    : VelocityMotor(0)  {
  (void)_alloc;
    }



   typedef int32_t _VelocityMotor_type;
  _VelocityMotor_type VelocityMotor;





  typedef boost::shared_ptr< ::serial_test::velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_test::velocity_<ContainerAllocator> const> ConstPtr;

}; // struct velocity_

typedef ::serial_test::velocity_<std::allocator<void> > velocity;

typedef boost::shared_ptr< ::serial_test::velocity > velocityPtr;
typedef boost::shared_ptr< ::serial_test::velocity const> velocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_test::velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_test::velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'serial_test': ['/home/nhan/my_ws/src/serial_test/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_test::velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_test::velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_test::velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_test::velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_test::velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_test::velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_test::velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87e9b3f456f7fcb4b57cfde083310f87";
  }

  static const char* value(const ::serial_test::velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87e9b3f456f7fcb4ULL;
  static const uint64_t static_value2 = 0xb57cfde083310f87ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_test::velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_test/velocity";
  }

  static const char* value(const ::serial_test::velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_test::velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 VelocityMotor\n\
";
  }

  static const char* value(const ::serial_test::velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_test::velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.VelocityMotor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_test::velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_test::velocity_<ContainerAllocator>& v)
  {
    s << indent << "VelocityMotor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.VelocityMotor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_TEST_MESSAGE_VELOCITY_H
