// Generated by gencpp from file vidu1/vidu1_srv1.msg
// DO NOT EDIT!


#ifndef VIDU1_MESSAGE_VIDU1_SRV1_H
#define VIDU1_MESSAGE_VIDU1_SRV1_H

#include <ros/service_traits.h>


#include <vidu1/vidu1_srv1Request.h>
#include <vidu1/vidu1_srv1Response.h>


namespace vidu1
{

struct vidu1_srv1
{

typedef vidu1_srv1Request Request;
typedef vidu1_srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vidu1_srv1
} // namespace vidu1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vidu1::vidu1_srv1 > {
  static const char* value()
  {
    return "2a5c7a37218262bae4fcfaa1007692aa";
  }

  static const char* value(const ::vidu1::vidu1_srv1&) { return value(); }
};

template<>
struct DataType< ::vidu1::vidu1_srv1 > {
  static const char* value()
  {
    return "vidu1/vidu1_srv1";
  }

  static const char* value(const ::vidu1::vidu1_srv1&) { return value(); }
};


// service_traits::MD5Sum< ::vidu1::vidu1_srv1Request> should match 
// service_traits::MD5Sum< ::vidu1::vidu1_srv1 > 
template<>
struct MD5Sum< ::vidu1::vidu1_srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::vidu1::vidu1_srv1 >::value();
  }
  static const char* value(const ::vidu1::vidu1_srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::vidu1::vidu1_srv1Request> should match 
// service_traits::DataType< ::vidu1::vidu1_srv1 > 
template<>
struct DataType< ::vidu1::vidu1_srv1Request>
{
  static const char* value()
  {
    return DataType< ::vidu1::vidu1_srv1 >::value();
  }
  static const char* value(const ::vidu1::vidu1_srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vidu1::vidu1_srv1Response> should match 
// service_traits::MD5Sum< ::vidu1::vidu1_srv1 > 
template<>
struct MD5Sum< ::vidu1::vidu1_srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::vidu1::vidu1_srv1 >::value();
  }
  static const char* value(const ::vidu1::vidu1_srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::vidu1::vidu1_srv1Response> should match 
// service_traits::DataType< ::vidu1::vidu1_srv1 > 
template<>
struct DataType< ::vidu1::vidu1_srv1Response>
{
  static const char* value()
  {
    return DataType< ::vidu1::vidu1_srv1 >::value();
  }
  static const char* value(const ::vidu1::vidu1_srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VIDU1_MESSAGE_VIDU1_SRV1_H
